
// Default habit icons using Material Icons names
// These are verified Material Design icon names that work on Android/Web
export const DEFAULT_HABIT_ICONS = [
  { name: 'fitness-center', label: 'Fitness' },
  { name: 'directions-run', label: 'Running' },
  { name: 'self-improvement', label: 'Meditation' },
  { name: 'menu-book', label: 'Reading' },
  { name: 'water-drop', label: 'Water' },
  { name: 'restaurant', label: 'Healthy Eating' },
  { name: 'bedtime', label: 'Sleep' },
  { name: 'work', label: 'Work' },
  { name: 'school', label: 'Study' },
  { name: 'brush', label: 'Art' },
  { name: 'music-note', label: 'Music' },
  { name: 'code', label: 'Coding' },
  { name: 'edit', label: 'Writing' },
  { name: 'camera', label: 'Photography' },
  { name: 'language', label: 'Language' },
  { name: 'favorite', label: 'Health' },
  { name: 'spa', label: 'Wellness' },
  { name: 'local-cafe', label: 'Coffee' },
  { name: 'smoking-rooms', label: 'Quit Smoking' },
  { name: 'phone', label: 'Phone' },
  { name: 'computer', label: 'Computer' },
  { name: 'videogame-asset', label: 'Gaming' },
  { name: 'sports-esports', label: 'Esports' },
  { name: 'sports-soccer', label: 'Soccer' },
  { name: 'sports-basketball', label: 'Basketball' },
  { name: 'pool', label: 'Swimming' },
  { name: 'directions-bike', label: 'Cycling' },
  { name: 'hiking', label: 'Hiking' },
  { name: 'nature', label: 'Nature' },
  { name: 'pets', label: 'Pets' },
  { name: 'cleaning-services', label: 'Cleaning' },
  { name: 'shopping-cart', label: 'Shopping' },
  { name: 'attach-money', label: 'Finance' },
  { name: 'savings', label: 'Savings' },
  { name: 'volunteer-activism', label: 'Volunteering' },
  { name: 'groups', label: 'Social' },
  { name: 'family-restroom', label: 'Family' },
  { name: 'child-care', label: 'Parenting' },
  { name: 'celebration', label: 'Celebration' },
  { name: 'star', label: 'Star' },
];
